# -*- coding: utf-8 -*-
"""Aula06/03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lCu-_tpsobIdkNF2kapT7ScklQs4Bc97

# **Aula 8**

## Atividade 1
"""

def saudacao(nome):
  print(f'Olá {nome}')

nome = input('Entre com seu nome: ')

saudacao(nome)

"""## Atividade 2"""

def alterna(n):
  fator, mult = -1,-1
  for i in range(n+1):
    print(i*mult, end=' ')
    mult *= fator
  print()

alterna(5)
alterna(9)
alterna(12)

"""## Atividade 3"""

def perimetro_retangulo(base,altura):
  return (base*2)+(altura*2)

print(perimetro_retangulo(2,3))

"""## Atividade 4"""

def saudacao(nome, mensagem):
  print(f'Olá {nome}! {mensagem}')

saudacao('Gustavo', 'Como você está?')

saudacao(mensagem='Suave?', nome='Jão')

"""## Atividade 5"""

def soma_pn(valores):
  soma_p,soma_n = 0,0
  for n in valores:
    if n >= 0:
      soma_p += n
    else:
      soma_n += n

  return soma_p, soma_n

valores = [2,-1,-4, 3]

soma_p,soma_n = soma_pn(valores)

print(f'soma dos positivos: {soma_p}\nsoma dos negativos: {soma_n}')

"""# Atividade 6"""

def somas(lista):
  soma = sum(lista)
  soma2 = sum([n**2 for n in lista])

  return soma, soma2

valores = [2,-1,-4, 3]
soma, soma2 = somas(valores)

print(f'soma: {soma}\nsoma2: {soma2}')